bcgov/House-Policy-STRDSS

frontend/src/app/features/components/access-request/access-request.component.html, frontend/src/app/features/components/access-request/access-request.component.scss, frontend/src/app/features/components/compliance-notice/compliance-notice.component.html, frontend/src/app/features/components/compliance-notice/compliance-notice.component.scss, frontend/src/app/features/components/delisting-request/delisting-request.component.html, frontend/src/app/features/components/delisting-request/delisting-request.component.scss, frontend/src/app/features/components/delisting-request/delisting-request.component.ts, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.scss, frontend/src/app/features/components/user-management/user-management.component.ts, frontend/src/styles.scss
Delisting and notice:
- Preview titles
- submit button color
- hr color
- remove second hr
- fix buttons in preview: paddings, order, placement
- fixed CC list bug on Delisting page
Access request:
- reduced width of a card
User management:
- Change switch's color when disabled
- rename Reject to Deny button
- fix colors and placement of buttons
Common styles:
- remove clear icon (x) from all dropdowns
=> Design review fixes

frontend/src/app/common/models/access-request-table-item.ts, frontend/src/app/common/models/access-request.ts, frontend/src/app/common/services/request-access.service.ts, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.ts
Approve Deny popups and related stuff. Correct representation of status in the table. Stylefixes.
=> Approve Deny popups and related stuff. Correct representation of status in the table. Stylefixes.

frontend/src/app/common/models/dropdown-option.ts, frontend/src/app/common/services/user-data.service.ts, frontend/src/app/features/components/compliance-notice/compliance-notice.component.ts, frontend/src/app/features/components/delisting-request/delisting-request.component.ts, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.scss, frontend/src/app/features/components/user-management/user-management.component.ts, frontend/src/styles.scss
Added Search and server-side paging to a UserManagement component. 
Fixed DSS-218(error message persists even if all is clear)
=> [DSS-146] UserManagement list & [DSS-218] bug

Test/UITest/SpecFlowProjectBDD/Features/SendNoticeOfTakedownWithoutADSSlisting.feature, Test/UITest/SpecFlowProjectBDD/Features/SendNoticeOfTakedownWithoutADSSlisting.feature.cs, Test/UITest/SpecFlowProjectBDD/Features/SendTakeDownRequestWithoutADSSListing.feature, Test/UITest/SpecFlowProjectBDD/Features/SendTakeDownRequestWithoutADSSListing.feature.cs, Test/UITest/SpecFlowProjectBDD/StepDefinitions/SendNoticeOfTakedownWithoutADSSlisting.cs, Test/UITest/SpecFlowProjectBDD/StepDefinitions/SendTakeDownRequestWithoutADSSListing.cs, Test/UITest/TestFrameWork/Models/IDirLogonModel.cs, Test/UITest/TestFrameWork/PageObjects/IDRLoginPage.cs, Test/UITest/TestFrameWork/SeleniumObjects/UIElement.cs, Test/UITest/XUnitTests/HousrSTRE2E.cs
Added logic to pass test when ExpectedResult=ActualResult. Fail otherwise. Code Cleanup. All tests passing
=> Refactoring/Test Harding

frontend/src/app/common/models/compliance-notice.ts, frontend/src/app/features/components/compliance-notice/compliance-notice.component.html, frontend/src/app/features/components/compliance-notice/compliance-notice.component.ts
Fixed DTO property that is responsible for the optional state
=> DSS-207 - BUG: Notice of Takedown - Host Email should not be required if related checkbox is selected

frontend/src/app/common/layout/layout.component.html, frontend/src/app/common/layout/layout.component.ts, frontend/src/app/common/models/dashboard-card.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/features/components/dashboard/dashboard.component.html
DSS-298 - Wrong boxes on a homepage for LG. Additionally added IDs for tiles and buttons for testing and fixed error with undefined currentUser entity
=> DSS-298 and stuff

frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/features/components/access-request/access-request.component.html, frontend/src/app/features/components/access-request/access-request.component.scss, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.ts
DSS-310, DSS-311, DSS-312. Additionally filtered the organizations dropdown by selected orgType.
=> DSS-310, 311, 312. +bonus

frontend/src/app/features/components/upload-listings/upload-listings.component.html, frontend/src/app/features/components/upload-listings/upload-listings.component.ts
- Added success message and form cleanup when the listings-file was updated successfuly
- Removed debug line
=> DSS-211: Upload Listing Data - small fixes

frontend/src/app/features/components/dashboard/dashboard.component.html, frontend/src/app/features/components/dashboard/dashboard.component.ts
hotfix - unable to navigate to a dashboard for some users (without `listing_file_upload` permission)
=> hotfix - unable to navigate to a dashboard

frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.html, frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.ts, frontend/src/app/common/models/user.ts, frontend/src/app/features/components/upload-listings/upload-listings.component.html, frontend/src/app/features/components/upload-listings/upload-listings.component.ts
For both `Upload Listing` and `Upload Listing History` pages
=> hotfix - remove Platform dropdown for platform users (DSS-441)

frontend/src/app/app.routes.ts, frontend/src/app/common/layout/layout.component.ts, frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.scss, frontend/src/app/common/models/listing-details.ts, frontend/src/app/common/services/listing-data.service.ts, frontend/src/app/features/components/compliance-notice/compliance-notice.component.scss, frontend/src/app/features/components/dashboard/dashboard.component.scss, frontend/src/app/features/components/delisting-request/delisting-request.component.scss, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.scss, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.scss, frontend/src/app/features/components/listings-table/listings-table.component.ts, frontend/src/app/features/components/upload-listings/upload-listings.component.scss, frontend/src/app/features/components/user-management/user-management.component.scss, frontend/src/styles.scss
- [DSS-421](https://hous-hpb.atlassian.net/browse/DSS-421) View Listing Details (Front end)
- [DSS-438](https://hous-hpb.atlassian.net/browse/DSS-438) Listing Actions History (FE)
- [DSS-439](https://hous-hpb.atlassian.net/browse/DSS-439) Legend for Details page (FE)
- [DSS-437](https://hous-hpb.atlassian.net/browse/DSS-437) Listing History (Front end)
=> Listing Details stories

frontend/src/app/app.routes.ts, frontend/src/app/common/models/compliance-notice.ts, frontend/src/app/common/models/listing-details.ts, frontend/src/app/common/services/delisting.service.ts, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.html, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.scss, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.ts, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.html, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.ts, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.ts, frontend/src/styles.scss
[DSS-424](https://hous-hpb.atlassian.net/browse/DSS-424) Send Notice of Non Compliance from listing view (FE)
[DSS-428](https://hous-hpb.atlassian.net/browse/DSS-428) Send Notice of Non-Compliance from listing details page (Front end)
Also defects:
[DSS-507](https://hous-hpb.atlassian.net/browse/DSS-507) (DEV) Business License mispelling in Search by dropdown
[DSS-515](https://hous-hpb.atlassian.net/browse/DSS-515) (Bug) Listings Detail Page - Should open in new tab
[DSS-506](https://hous-hpb.atlassian.net/browse/DSS-506) (DEV) Showing 25 of 0 listings - Rows per Page should be 0 when no listings returned
[DSS-514](https://hous-hpb.atlassian.net/browse/DSS-514) (Bug) Listings Detail Page - Last Updated Date is not populated
Bonus:
Search Listings input now sends request by pushing `Enter` …
=> DSS-424, DSS-428: Send Notice of Non Compliance

frontend/src/app/common/services/user-data.service.ts, frontend/src/app/features/components/user-management/user-details/user-details.component.ts
Bugfix for parent story: [DSS-500:](https://hous-hpb.atlassian.net/browse/DSS-500) (FE) User Information Page
=> DSS-500: (FE) User Information Page - Adopted `isEnabled` property

frontend/src/app/common/layout/layout.component.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/common/services/top-menu.service.ts
[DSS-596](https://hous-hpb.atlassian.net/browse/DSS-596) User Guide Page
=> DSS-596: User Guide Page

frontend/src/app/common/components/upload-file/upload-file.component.html, frontend/src/app/common/components/upload-file/upload-file.component.scss, frontend/src/app/common/components/upload-file/upload-file.component.ts, frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.html, frontend/src/app/common/models/listing-upload-history-record.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/common/services/listing-data.service.ts, frontend/src/app/common/services/top-menu.service.ts, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.scss, frontend/src/app/features/components/listings-table/listings-table.component.scss, frontend/src/app/features/components/upload-listings/upload-listings.component.html, frontend/src/app/features/components/upload-listings/upload-listings.component.scss, frontend/src/app/features/components/upload-listings/upload-listings.component.ts
[DSS-605](https://hous-hpb.atlassian.net/browse/DSS-605): Upload Takedown Confirmation Data (CEU Admin) - FE Development
[DSS-609](https://hous-hpb.atlassian.net/browse/DSS-609): FE: Update Listing Status after Takedown Confirmation
[DSS-611](https://hous-hpb.atlassian.net/browse/DSS-611): FE: Update Platform Upload History to Include Takedown Upload (CEU)
[DSS-613](https://hous-hpb.atlassian.net/browse/DSS-613): FE: Update Platform Upload History to Include Takedown Upload (Platform)
[DSS-615](https://hous-hpb.atlassian.net/browse/DSS-615): FE: Update Listing Action History after Takedown Confirmation
[DSS-607](https://hous-hpb.atlassian.net/browse/DSS-607): Upload Takedown Confirmation Data (Platform) - Front end development
[DSS-691](https://hous-hpb.atlassian.net/browse/DSS-691): …
=> Takedown Upload and History

frontend/src/app/common/models/dropdown-option.ts, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.ts, frontend/src/styles.scss
[DSS-658](https://hous-hpb.atlassian.net/browse/DSS-658): FE: Filter Listings by Location - Group communities
=> DSS-658: FE: Filter Listings by Location - Group communities

frontend/src/app/app.component.html, frontend/src/app/app.component.scss, frontend/src/app/app.component.ts, frontend/src/app/common/consts/error-interceptor.const.ts
[DSS-695](https://hous-hpb.atlassian.net/browse/DSS-695): Front End failure to connect to Keycloak does not generate an User error or throw an exception to aid in troubleshooting when there is a Keycloak connectivity issue
=> DSS-695: handle errors that occure before the main application has been loaded

frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.ts
[DSS-658](https://hous-hpb.atlassian.net/browse/DSS-658): FE: Filter Listings by Location - Group communities - Extra requirements
=> DSS-658 FE: Filter Listings by Location - Group communities - Extra requirements

frontend/src/app/features/components/listings-table/listings-table.component.ts
[DSS-658](https://hous-hpb.atlassian.net/browse/DSS-658): FE: Filter Listings by Location - Group communities
=> DSS-658 FE: Filter Listings by Location - Group communities - Fixes and order corrections

frontend/src/app/features/components/user-management/user-details/user-details.component.ts, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.scss, frontend/src/app/features/components/user-management/user-management.component.ts
[DSS-530](https://hous-hpb.atlassian.net/browse/DSS-530): Sort on page view
_Additionally sorted data in UserDetails page dropdowns alphabetically for better user-experience_
=> DSS-530: Sort on page view

frontend/src/app/features/components/compliance-notice/compliance-notice.component.ts
[DSS-317](https://hous-hpb.atlassian.net/browse/DSS-317): Can enter email and check box on Non of non-compliance
=> DSS-317: Can enter email and check box on Non of non-compliance

frontend/src/app/common/consts/validators.const.ts, frontend/src/app/features/components/delisting-request/delisting-request.component.ts
[DSS-324](https://hous-hpb.atlassian.net/browse/DSS-324): Takedown Request and Non Compliance notices issues
=> DSS-324: Takedown Request and Non Compliance notices issues

frontend/src/app/features/components/compliance-notice/compliance-notice.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.html
[DSS-324](https://hous-hpb.atlassian.net/browse/DSS-324): Takedown Request and Non Compliance notices issues (Notice)
Bonus - IDs for buttons and other controls on a listings page
=> DSS-324: Takedown Request and Non Compliance notices issues, and more

frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.scss, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.scss
[DSS-668](https://hous-hpb.atlassian.net/browse/DSS-668): Add flags visuals to legend
=> DSS-668: Add flags visuals to legend

frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/upload-business-license/upload-business-license.component.html
Hotfix: 
- Wrong Upload date format (BL and listing).
- Buttons for notice and takedown are shown on a listing details for CEU
=> Hotfix: 1)Wrong Upload date format (BL and listing). 2)Buttons for notice and takedown are shown on a listing details for CEU

frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.html, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.scss, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.ts, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.html, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.scss, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.ts
[DSS-796](https://hous-hpb.atlassian.net/browse/DSS-796) :FE: Enhancement to send notice/takedown in aggregated listings
=> DSS-796: FE: Enhancement to send notice/takedown in aggregated listings

frontend/src/app/common/services/business-licence.service.ts, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.ts, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.ts, frontend/src/app/features/components/export-listings/export-listings.component.ts, frontend/src/app/features/components/upload-business-license/upload-business-license.component.html, frontend/src/app/features/components/upload-business-license/upload-business-license.component.ts
[DSS-770](https://hous-hpb.atlassian.net/browse/DSS-770): FE: Add downloadable error file to business licence upload history
=> DSS-770: FE: Add downloadable error file to business licence upload history

frontend/src/app/common/models/bl-search-result-row.ts, frontend/src/app/common/models/listing-details.ts, frontend/src/app/common/models/listing-table-row.ts, frontend/src/app/common/services/business-licence.service.ts, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.scss, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.scss, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.scss, frontend/src/styles.scss
[DSS-764](https://hous-hpb.atlassian.net/browse/DSS-764) FE: Link Business Licence record
[DSS-765](https://hous-hpb.atlassian.net/browse/DSS-765) FE: Search for Business Licence record
[DSS-766](https://hous-hpb.atlassian.net/browse/DSS-766) FE: Unlink Business Licence record
=> DSS-764,DSS-766,DSS-765: Link/Unlink/Search Business Licence records

frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.html, frontend/src/app/common/listing-upload-history-table/listing-upload-history-table.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.ts
DSS-807: When filter is changed, results don't return to page 1
=> DSS-809: No spinning wheel on Platform history page. DSS-807: When filter is changed, results don't return to page 1

frontend/src/app/common/layout/layout.component.html, frontend/src/app/common/layout/layout.component.scss, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.scss, frontend/src/styles.scss
[DSS-836](https://hous-hpb.atlassian.net/browse/DSS-836): FE Print detailed listing page
=> DSS-836: FE Print detailed listing page

frontend/src/app/app.routes.ts, frontend/src/app/common/models/aps-user.ts, frontend/src/app/common/services/user-data.service.ts, frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.html, frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.scss, frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.spec.ts, frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.ts, frontend/src/app/features/components/user-management/user-management.component.html, frontend/src/app/features/components/user-management/user-management.component.scss, frontend/src/app/features/components/user-management/user-management.component.ts, frontend/src/styles.scss
[DSS-812](https://hous-hpb.atlassian.net/browse/DSS-812): APS user registration - FE
TODO: Implement redirection to a newly created user's details (User Details page)
=> DSS-812: APS user registration - FE

frontend/src/app/common/layout/layout.component.scss, frontend/src/app/features/components/compliance-notice/compliance-notice.component.html, frontend/src/app/features/components/compliance-notice/compliance-notice.component.ts, frontend/src/app/features/components/delisting-request/delisting-request.component.html, frontend/src/app/features/components/delisting-request/delisting-request.component.ts, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.scss, frontend/src/styles.scss
[DSS-849](https://hous-hpb.atlassian.net/browse/DSS-849): Aggregate listing view displays too large
[DSS-457](https://hous-hpb.atlassian.net/browse/DSS-457): Menu header does not return to form
=> DSS-849: Aggregate listing view displays too large, DSS-457: Menu header does not return to form

frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.ts
[DSS-812](https://hous-hpb.atlassian.net/browse/DSS-812): APS user registration - FE
=> [DSS-812] Redirect to UserDetails after creation of a new APS user

frontend/src/app/common/consts/permissions.const.ts, frontend/src/app/common/models/dashboard-card.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/common/services/top-menu.service.ts, frontend/src/app/features/components/dashboard/dashboard.component.html, frontend/src/app/features/components/dashboard/dashboard.component.scss, frontend/src/app/features/components/dashboard/dashboard.component.ts
[DSS-723](https://hous-hpb.atlassian.net/browse/DSS-723): Updates to home page cards and menu items
=> DSS-723: Updates to home page cards and menu items

frontend/src/app/app.routes.ts, frontend/src/app/common/models/platform.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/common/services/organization.service.spec.ts, frontend/src/app/common/services/organization.service.ts, frontend/src/app/common/services/request-access.service.ts, frontend/src/app/common/services/top-menu.service.ts, frontend/src/app/features/components/access-request/access-request.component.ts, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.ts, frontend/src/app/features/components/platform-management/add-new-platform/add-new-platform.component.html, frontend/src/app/features/components/platform-management/add-new-platform/add-new-platform.component.scss, frontend/src/app/features/components/platform-management/add-new-platform/add-new-platform.component.spec.ts, frontend/src/app/features/components/platform-management/add-new-platform/add-new-platform.component.ts, frontend/src/app/features/components/platform-management/add-sub-platform/add-sub-platform.component.spec.ts, frontend/src/app/features/components/platform-management/add-sub-platform/add-sub-platform.component.ts, frontend/src/app/features/components/platform-management/edit-platform/edit-platform.component.html, frontend/src/app/features/components/platform-management/edit-platform/edit-platform.component.spec.ts, frontend/src/app/features/components/platform-management/edit-platform/edit-platform.component.ts, frontend/src/app/features/components/platform-management/platform-management.component.html, frontend/src/app/features/components/platform-management/platform-management.component.scss, frontend/src/app/features/components/platform-management/platform-management.component.spec.ts, frontend/src/app/features/components/platform-management/platform-management.component.ts, frontend/src/app/features/components/platform-management/view-platform/view-platform.component.html, frontend/src/app/features/components/platform-management/view-platform/view-platform.component.spec.ts, frontend/src/app/features/components/platform-management/view-platform/view-platform.component.ts, frontend/src/app/features/components/upload-business-license/upload-business-license.component.ts, frontend/src/app/features/components/user-management/add-aps-user/add-aps-user.component.ts, frontend/src/app/features/components/user-management/user-details/user-details.component.ts, frontend/src/app/features/components/user-management/user-management.component.ts
[DSS-360](https://hous-hpb.atlassian.net/browse/DSS-360): Manage Platforms List - FE Development
[DSS-362](https://hous-hpb.atlassian.net/browse/DSS-362): Add new Platform - FE Development
=> DSS-360, DSS-362:: Manage and add Platforms List - FE Development

frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.html, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.ts, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.html, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.ts
[DSS-936](https://hous-hpb.atlassian.net/browse/DSS-936): Unblock takedowns for inactive listings
=> DSS-936: Unblock takedowns for inactive listings

frontend/src/app/features/components/dashboard/dashboard.component.scss
[DSS-890](https://hous-hpb.atlassian.net/browse/DSS-890): Home Page Tile Positioning With 1920 Screen Width
=> DSS-890: Home Page Tile Positioning With 1920 Screen Width

frontend/src/app/common/models/platform.ts, frontend/src/app/features/components/platform-management/add-new-platform/add-new-platform.component.ts, frontend/src/app/features/components/platform-management/add-sub-platform/add-sub-platform.component.html, frontend/src/app/features/components/platform-management/add-sub-platform/add-sub-platform.component.ts, frontend/src/app/features/components/platform-management/edit-platform/edit-platform.component.html, frontend/src/app/features/components/platform-management/edit-platform/edit-platform.component.ts, frontend/src/app/features/components/platform-management/edit-sub-platform/edit-sub-platform.component.html, frontend/src/app/features/components/platform-management/edit-sub-platform/edit-sub-platform.component.ts, frontend/src/app/features/components/platform-management/platform-management.component.html, frontend/src/app/features/components/platform-management/view-platform/view-platform.component.html
[DSS-226](https://hous-hpb.atlassian.net/browse/DSS-226): Manage Platforms
=> Emails for SubPlatforms, minor fixes.

frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.ts, frontend/src/app/features/components/listings-table/listings-table.component.ts
Covered pages:
- Aggregated Listings
- Listings
=> Fixed: overuse of the paginator - search doesn't work in some cases

frontend/src/app/app.routes.ts, frontend/src/app/common/consts/permissions.const.ts, frontend/src/app/common/models/jurisdiction.ts, frontend/src/app/common/services/dashboard.service.ts, frontend/src/app/common/services/organization.service.ts, frontend/src/app/common/services/request-access.service.ts, frontend/src/app/common/services/roles.service.ts, frontend/src/app/common/services/selected-listings-state.service.ts, frontend/src/app/common/services/top-menu.service.ts, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.html, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.scss, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.spec.ts, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.ts, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.html, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.scss, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.spec.ts, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.ts, frontend/src/app/features/components/manage-jurisdictions/update-local-gvernment-information/update-local-gvernment-information.component.html, frontend/src/app/features/components/manage-jurisdictions/update-local-gvernment-information/update-local-gvernment-information.component.scss, frontend/src/app/features/components/manage-jurisdictions/update-local-gvernment-information/update-local-gvernment-information.component.spec.ts, frontend/src/app/features/components/manage-jurisdictions/update-local-gvernment-information/update-local-gvernment-information.component.ts, frontend/src/app/features/components/platform-management/platform-management.component.html
[DSS-950](https://hous-hpb.atlassian.net/browse/DSS-950): FE: Manage Jurisdictions - List
[DSS-952](https://hous-hpb.atlassian.net/browse/DSS-952): FE: Update Local Governments
[DSS-954](https://hous-hpb.atlassian.net/browse/DSS-954): FE: Update Jurisdictions
=> DSS-950, DSS-952, DSS-954: FE: Manage Jurisdictions - List, Update LG, Update Jurisdiction

frontend/src/app/common/pipes/text-cleanup.pipe.spec.ts, frontend/src/app/common/pipes/text-cleanup.pipe.ts, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.ts, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.html, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.ts, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.html, frontend/src/app/features/components/platform-management/view-platform/view-platform.component.html, frontend/src/app/features/components/roles-list/role-details/role-details.component.scss
[DSS-783](https://hous-hpb.atlassian.net/browse/DSS-783): Unexpected Comma in Platform Address Field in Address History Section on Listing Details Page
[DSS-1005](https://hous-hpb.atlassian.net/browse/DSS-1005): (FE) Update Jurisdiction Information - Duplicate field name
[DSS-1004](https://hous-hpb.atlassian.net/browse/DSS-1004): (FE) Manage Jurisdictions List: Hide Edit for users with Read permissions
[DSS-780](https://hous-hpb.atlassian.net/browse/DSS-780): Date Format is Inconsistent on The Listing Details page
[DSS-998](https://hous-hpb.atlassian.net/browse/DSS-998): Platform Details Page Misspelling
=> DSS-783, DSS-1005, DSS-1004, DSS-780, DSS-998: A few small fixes

frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html
Now it will show up when it is 90 an more days
=> 90 days fix

frontend/src/app/features/components/listings-table/listings-table.component.html
(cherry picked from commit 7155ef4c491e34519f88944cf0462676e567ec44)
=> FIX: LastActionDate on Listings Table page

frontend/src/app/common/models/jurisdiction.ts, frontend/src/app/features/components/manage-jurisdictions/manage-jurisdictions.component.html, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.html, frontend/src/app/features/components/manage-jurisdictions/update-jurisdiction-information/update-jurisdiction-information.component.ts
[DSS-1041](https://hous-hpb.atlassian.net/browse/DSS-1041): FE: Add STRAA Exempt to Manage Jurisdictions
=> DSS-1041: STRAA Exempt and IsActive flags for Jurisdictions

frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.scss, frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.scss
- Listings page
- Aggregated Listings page
[DSS-1017](https://hous-hpb.atlassian.net/browse/DSS-1017): Expand pagination of search results
=> DSS-1017: Expand pagination of search results. Listing pages.

frontend/src/app/common/layout/layout.component.html, frontend/src/app/features/components/bulk-compliance-notice/bulk-compliance-notice.component.html, frontend/src/app/features/components/bulk-takedown-request/bulk-takedown-request.component.html, frontend/src/app/features/components/delisting-request/delisting-request.component.html, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, frontend/src/app/features/components/listings-table/listings-table.component.html
This touches on several pages but fixes are small tweaks for accessibility.  DSS 704-707
=> dss-907 front end accessibility fixes includes dss-704,705,706

frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html
Changed column names and expanded tooltip
=> feature/dss-1026 Changes to Aggregated Listings

frontend/src/app/features/components/listings-table/listings-table.component.html, frontend/src/app/features/components/listings-table/listings-table.component.scss, frontend/src/app/features/components/listings-table/listings-table.component.ts
[DSS-1058](https://hous-hpb.atlassian.net/browse/DSS-1058): FE: Contact Host should be available from the Listings Page
=> DSS-1058: FE: Contact Host should be available from the Listings Page

frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.html, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.scss, frontend/src/app/features/components/listings-table/aggregated-listings-table/aggregated-listings-table.component.ts, frontend/src/app/features/components/send-compliance-order/send-compliance-order.component.ts
[DSS-1060](https://hous-hpb.atlassian.net/browse/DSS-1060): Issue with Hyperlinks in comments
[DSS-1074](https://hous-hpb.atlassian.net/browse/DSS-1074): FE: Add multi-host click through to Aggregated Listings page
=> DSS-1060, DSS-1074

.github/CODEOWNERS, frontend/src/app/common/models/listing-details.ts, frontend/src/app/features/components/listings-table/listing-details/listing-details.component.html, server/StrDss.Common/Constants.cs, server/StrDss.Data/Entities/DssDbContext.cs, server/StrDss.Data/Entities/DssRentalListing.cs, server/StrDss.Data/Entities/DssRentalListingVw.cs, server/StrDss.Model/IUploadLine.cs, server/StrDss.Model/RentalListingExportDto.cs, server/StrDss.Model/RentalReportDtos/RentalListingViewDto.cs, server/StrDss.Service/TakedownConfirmationService.cs, server/StrDss.Service/UploadDeliveryService.cs
[DSS-1084](https://hous-hpb.atlassian.net/browse/DSS-1084)
- Added take down reason attribute to the API and front end
=> DSS-1084 Platforms upload expanded takedown report

frontend/src/app/common/services/registration.service.ts, frontend/src/app/features/components/registration-validation-history/registration-validation-history.component.html, frontend/src/app/features/components/registration-validation-history/registration-validation-history.component.scss, frontend/src/app/features/components/registration-validation-history/registration-validation-history.component.ts, server/StrDss.Api/Controllers/RegistrationController.cs, server/StrDss.Data/Repositories/UploadDeliveryRepository.cs, server/StrDss.Service/UploadDeliveryService.cs
- https://hous-hpb.atlassian.net/browse/DSS-1089
- https://hous-hpb.atlassian.net/browse/DSS-1093
=> DSS-1089-1093 Registration Validation - Platforms Uploads Report   

server/StrDss.Test/AutoDomainDataBuilder/RentalListingRowUntypedBuilder.cs
Added fields to RentalList row to pass unit tests
=> Update for Unit Tests

server/StrDss.Data/Mappings/ModelToEntityProfile.cs, server/StrDss.Service/HttpClients/RegistrationAPI/BaseRegistrationApi.cs, server/StrDss.Service/HttpClients/RegistrationAPI/RegistrationApi.g.cs, server/StrDss.Service/HttpClients/RegistrationAPI/registration-api.nswag, server/StrDss.Service/PermitValidationService.cs, server/StrDss.Service/RegistrationService.cs, server/StrDss.Service/RentalListingReportService.cs, server/StrDss.Test/AutoDomainDataBuilder/RentalListingRowUntypedBuilder.cs
Added functionality to check registration validity in the monthly listing report
=> Listing Report Reg Check

server/StrDss.Service/HttpClients/ServiceCollectionExtension.cs
Setting timeout and defaults for reg validation api call
=> Reg Val Timeout

server/StrDss.Service/HttpClients/ServiceCollectionExtension.cs
Increasing timeout of call to 10 minutes
=> Timeout Increase

server/StrDss.Service/PermitValidationService.cs
Fixes to build due to merging main back into branch
=> Merge Fixes

server/StrDss.Data/Repositories/RentalListingReportRepository.cs
Added a check to the report list to make sure it isn't empty before we process it.
=> Empty List Fix

server/StrDss.Service/PermitValidationService.cs
Removed parsing for error changes as they are throwing
=> Fix for issue with changes

database/ddl/STR_DSS_Incremental_DB_DLL_21_ROLLBACK.sql, database/utility/upload_history_test.sql, server/StrDss.Service/RentalListingReportService.cs
Always setting a registration error text now, and also sending an email for the validation report being ready.
=> DSS-1142 Fix

server/StrDss.Service/RentalListingReportService.cs
Added a Task to SendEmails so that the DBContext wouldn't get dropped causing a crash sending the emails
=> Fix Email Crash

server/StrDss.Service/UploadDeliveryService.cs
Missing comma put in to separate headers correctly
=> Added Comma

frontend/src/app/features/components/validate-registration-data/validate-registration-data.component.ts
Added comment to make a change for fake deployment
=> No-Op Change
